### ISSUE TITLE
Look for alternatives to bintray to publish artifacts

### ISSUE THREAD

**Issue by labra** [weso/shaclex#390]
We are currently publishing the binaries in Bintray but it seems the service will be [no longer available after 1st May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Help or comments are greatly appreciated.

**Comment by thewillyhuman** [comment]
Commented here https://github.com/weso/shex-s/issues/185#issuecomment-774449100 a possible solution.

**Comment by labra** [comment]
We are already publishing the binaries using github packages. 

There is one missing step to automate the publication of the binaries using github-actions once a release is created. Once it works, we will close this issue. 

We created a specific issue for it #409

**Comment by berezovskyi** [comment]
Thank you for quickly finding a fallback solution! Could you please consider deploying to Central via OSSRH, please?

GH requires authentication even to access packages from public artifacts. We publish our libraries to Central and they [discourage](https://central.sonatype.org/publish/requirements/#a-complete-example-pom) from including dependencies via other repositories (seems very wise in the light of Bintray's demise) and I guess token-walled GH will be a non-starter. We also ran into [problems](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574043) accessing the token in question from our builds on Github Actions.

**Comment by labra** [comment]
Yes, we noticed those problems also and we are working to publish the binaries in Sonatype. We are _almost_ there as we have already published some of them with Mark Iantorno's help: https://oss.sonatype.org/#nexus-search;quick~weso

**Comment by labra** [comment]
The shaclex binaries are now published at [Sonatype](https://oss.sonatype.org/#view-repositories;releases~browsestorage) and they are no longer published as github packages so we can close this issue. 

As an example, the latest version of Shaclex is available at [es.weso;shaclex_2.13_0.1.102](https://oss.sonatype.org/service/local/repositories/releases/content/es/weso/shaclex_2.12/0.1.102/shaclex_2.12-0.1.102.jar):

```xml
<dependency>
  <groupId>es.weso</groupId>
  <artifactId>shaclex_2.13</artifactId>
  <version>0.1.102</version>
</dependency>
```
