### ISSUE TITLE
Swagger documentation points to old server location

### ISSUE THREAD

**Issue by AlasdairGray** [weso/shaclex#424]
The [Swagger doc page](https://app.swaggerhub.com/apis-docs/labra/rdfshape/1.0.1#/default/post_validate) uses the old server location (http://rdfshape.weso.es/api/). I believe the correct value should now be https://api.rdfshape.weso.es/api/.

**Comment by ulitol97** [comment]
That Swagger Hub page is currently outdated, as we changed the location of the API Docs of RDFShape.
You can now find them in: https://app.swaggerhub.com/apis/weso/RDFShape. Anyway, I'm afraid this API docs are currently incomplete as the API has suffered many changes and we are trying to update the docs in an automated way.

For more issues regarding the RDFShape API you may head to the [API repo](https://github.com/weso/rdfshape-api).

**Comment by ulitol97** [comment]
API Docs are no longer incomplete/outdated, see:
- https://github.com/weso/rdfshape-api/pull/292
- https://app.swaggerhub.com/apis/weso/RDFShape/
